import type { TranslationSchema } from './en';

const ko: TranslationSchema = {
	meta: { siteTitle: 'EDDI', siteDescription: 'EDDI — 엔터프라이즈 AI 오케스트레이터. 구성 기반, Java 네이티브 AI 미들웨어, Quarkus 기반 (v6.0.0-RC1 프리뷰).' },
	nav: { features: '기능', docs: '문서', solutions: '솔루션', getStarted: '시작하기', eddiManager: 'EDDI 매니저', eddiManagerDesc: '비주얼 에이전트 관리 UI', mcpServer: 'MCP 서버', mcpServerDesc: '48개 AI 네이티브 제어 도구', configAsCode: 'Config-as-Code', configAsCodeDesc: 'JSON 구성, Java 컴파일 불필요', securityFirst: '보안 우선', securityFirstDesc: 'Vault, 감사 추적, eval() 없음', performance: '성능', performanceDesc: 'Java 25 가상 스레드', multiAgent: '멀티 에이전트', multiAgentDesc: '의도 라우팅 및 디스커버리', observability: '관측성', observabilityDesc: '파이프라인 로그 및 감사 추적', codeQuality: '코드 품질', codeQualityDesc: '1,500+ 테스트, 실패 제로', aiReady: 'AI 대응', aiReadyDesc: '코딩 에이전트를 위한 설계', viewAllFeatures: '모든 기능 보기 →', whyEddi: '왜 EDDI인가?', whyEddiDesc: '유일한 JVM 네이티브 비주얼 AI 미들웨어', vsAlternatives: '대안 비교', vsAlternativesDesc: 'Spring AI, Flowise, n8n과 비교', euAiAct: 'EU AI법', euAiActDesc: '규정 준수 및 거버넌스', useCases: '활용 사례', useCasesDesc: '실제 배포 패턴', allFeatures: '모든 기능', mcpServerMobile: 'MCP 서버 (48개 도구)', resources: '리소스', documentation: '문서 ↗', github: 'GitHub ↗', switchToLightMode: '라이트 모드로 전환', switchToDarkMode: '다크 모드로 전환' },
	common: { getStartedCta: '시작하기 →', viewOnGithub: 'GitHub에서 보기 ↗', bannerBadge: '새로운', bannerText: 'EDDI v6.0.0-RC1 개발자 프리뷰가 출시되었습니다!', bannerLink: '시작하기', notFoundTitle: '페이지를 찾을 수 없습니다', notFoundDesc: '찾고 계신 AI 오케스트레이션 경로가 연결 해제되었거나 이동되었습니다.', notFoundCta: '시스템으로 돌아가기' },
	footer: { tagline: '엔터프라이즈 AI 오케스트레이터', subtitle: '구성 기반. Java 네이티브. 프로덕션 대응.', redHatCertified: 'Red Hat 인증 컨테이너', apache2: 'Apache 2.0 라이선스', tests: '1,500+ 테스트 · 실패 제로', techStack: 'Java 25 · Quarkus · LangChain4j', platform: '플랫폼', develop: '개발', resourcesCol: '리소스', featuresOverview: '기능 개요', mcpServer: 'MCP 서버', configAsCode: 'Config-as-Code', securityFirst: '보안 우선', performanceLink: '성능', multiAgent: '멀티 에이전트', gettingStarted: '시작하기', documentation: '문서 ↗', githubLink: 'GitHub ↗', whyEddi: '왜 EDDI인가?', vsAlternatives: '대안 비교', euAiAct: 'EU AI법', useCases: '활용 사례', initiated: '비엔나에서 시작. 유럽에서 ❤️로 개발. 세계를 위해 만들다.' },
	newsletter: { title: '최신 소식 받기', description: '새 릴리스, 기능 및 엔터프라이즈 AI 오케스트레이션 모범 사례에 대한 업데이트를 받으세요. 스팸 없음 — 시그널만.', compactTitle: '뉴스레터', compactDescription: 'EDDI 릴리스 및 AI 오케스트레이션 인사이트를 받아보세요.' },
	home: {
		title: '엔터프라이즈 AI 오케스트레이터', heroTitle: '엔터프라이즈', heroHighlight: 'AI 오케스트레이터',
		heroTagline: '구성 기반. Java 네이티브. 비주얼 관리. JVM 위에 네이티브 구축된 유일한 AI 미들웨어 — 현재 <strong>v6.0.0-RC1 프리뷰</strong> 중.',
		problemTitle: '문제', problemDesc: '엔터프라이즈 Java에는 <strong>비주얼 AI 오케스트레이션 미들웨어가 없습니다</strong>. 팀은 고통스럽고 파편화된 라이프사이클에 갇혀 있습니다:', problemCard1Title: '프로토타입의 함정', problemCard1Desc: '팀은 Python/Flowise/n8n으로 프로토타입을 만들고 — 프로덕션을 위해 <strong>모든 것을 Java로 처음부터 다시 작성</strong>합니다. 비주얼 프로토타입은 완전히 폐기됩니다.', problemCard2Title: '보일러플레이트 피로', problemCard2Desc: 'Spring AI나 LangChain4j를 사용하면 REST 컨트롤러, 인증 레이어, 상태 관리를 <strong>처음부터</strong> 구축해야 합니다. 모든 프롬프트 조정에 재컴파일이 필요합니다.', problemCard3Title: 'BPMN 마찰', problemCard3Desc: '비결정론적 AI 에이전트를 Camunda/Temporal의 결정론적 워크플로우에 강제하면 <strong>심각한 임피던스 불일치</strong>와 취약한 아키텍처가 발생합니다.',
		solutionTitle: '솔루션', solutionDesc: 'EDDI는 Java 생태계의 <strong>절대적 공백</strong>을 채웁니다 — 비주얼 관리 UI를 갖춘 배포 가능한 미들웨어 플랫폼:', sol1Title: 'Configuration-as-Code', sol1Desc: '에이전트 로직, 파이프라인, 도구 정의는 <strong>JSON 구성</strong>입니다 — 컴파일된 Java가 아닙니다. 프롬프트 엔지니어가 React UI 또는 REST API를 통해 즉시 반복하며, Java 코드를 건드릴 필요가 없습니다.', sol2Title: '48개 MCP 도구', sol2Desc: 'EDDI는 <strong>Model Context Protocol</strong>을 통해 기능을 노출합니다 — Claude Desktop과의 상호작용을 가능하게 합니다. 에이전트는 <strong>외부 MCP 도구를 소비</strong>할 수도 있습니다.', sol3Title: '보안 우선', sol3Desc: '<code>eval()</code> 없음, 이스케이프 없음. Vault 통합, URL 검증, 암호화 감사 추적은 <strong>아키텍처 기반</strong>입니다.', sol4Title: '관측성', sol4Desc: '모든 파이프라인 단계가 <strong>불변 감사 추적</strong>에 기록됩니다 — 토큰, 비용, 타이밍, 도구 호출. 완전한 CQRS 텔레메트리 원장.', sol5Title: '엔터프라이즈 동시성', sol5Desc: 'Quarkus에서의 Java 25 가상 스레드. I/O 바운드 LLM 워크로드를 위한 <strong>수백만 개의 경량 스레드</strong>. 이벤트 루프 블로킹 없음, 단일 스레드 병목 없음.', sol6Title: '멀티 에이전트 오케스트레이션', sol6Desc: '의도 기반 에이전트 디스커버리, 관리 대화, 에이전트 트리거, A/B 라우팅. <strong>의도+사용자당 하나의 대화</strong>, 자동 생성 및 자동 관리.',
		trustedTitle: '신뢰와 인증', trustRedHat: 'Red Hat 인증 컨테이너', trustRedHatDesc: 'IBM 인증 Docker 이미지', trustApache: 'Apache 2.0 라이선스', trustApacheDesc: '100% 오픈소스, 엔터프라이즈 대응', trustTests: '1,500+ 테스트 · 0 실패', trustTestsDesc: '엄격한 CI/CD 및 코드 커버리지',
		techTitle: '검증된 기술로 구축', techJava: 'Java 25', techJavaDesc: '엔터프라이즈 런타임', techQuarkus: 'Quarkus', techQuarkusDesc: '클라우드 네이티브, 빠른', techLangchain: 'LangChain4j', techLangchainDesc: '20+ LLM 프로바이더', techMongo: 'MongoDB', techMongoDesc: '문서 저장소', techPostgres: 'PostgreSQL', techPostgresDesc: '관계형 저장소', techDocker: 'Docker', techDockerDesc: '컨테이너 대응', techK8s: 'Kubernetes', techK8sDesc: '오케스트레이션', techOpenshift: 'OpenShift', techOpenshiftDesc: 'Red Hat 인증',
		nextStepsTitle: '다음 단계', nextGetStartedTitle: '5분 만에 시작하기', nextGetStartedDesc: 'EDDI를 설치하고, 첫 번째 에이전트를 만들고, 대화를 시작하세요.', nextFeaturesTitle: '모든 기능 탐색', nextFeaturesDesc: 'Config-as-Code, MCP 도구, 보안, 관측성 등.', nextWhyTitle: '왜 EDDI인가?', nextWhyDesc: '구성 기반 AI 오케스트레이션이 코드 우선 접근보다 나은 이유.', nextDocsTitle: '문서 보기 ↗', nextDocsDesc: '아키텍처, MCP 도구, REST API, 배포 가이드 등.',
		faqTitle: '자주 묻는 질문',
		faq1Q: 'EDDI란 무엇인가요?', faq1A: 'EDDI는 Quarkus와 Java 25 기반의 오픈소스 JVM 네이티브 AI 오케스트레이션 미들웨어입니다. 기업 팀이 컴파일된 코드 대신 JSON 구성을 사용하여 AI 에이전트를 구축, 구성, 배포할 수 있게 합니다. EDDI는 <strong>프로덕션 대응 React 관리 UI</strong>(EDDI 매니저), 내장 REST API, 대화 상태 관리, 보안(OIDC/Keycloak), 불변 감사 추적, 48개 MCP 도구를 갖춘 완전한 플랫폼을 제공합니다 — 모두 Docker 또는 Kubernetes로 배포 가능.',
		faq2Q: 'EDDI는 Spring AI나 LangChain4j와 어떻게 다른가요?', faq2A: 'Spring AI와 LangChain4j는 훌륭한 <strong>라이브러리</strong>입니다 — EDDI는 실제로 내부에서 LangChain4j를 사용합니다. 핵심 차이점은 EDDI가 <strong>배포 가능한 미들웨어 플랫폼</strong>이지 라이브러리가 아니라는 것입니다. Spring AI로는 REST 컨트롤러, 인증, 대화 상태 관리, 감사 로그, 관리 UI를 직접 구축해야 합니다. EDDI는 이 모든 것을 바로 사용할 수 있게 제공합니다.',
		faq3Q: 'EDDI는 엔터프라이즈 프로덕션 사용에 준비되어 있나요?', faq3A: '네. EDDI는 Java 25와 Quarkus에서 실행되며, I/O 바운드 동시성을 위해 가상 스레드를 활용합니다. MongoDB와 PostgreSQL을 지원하고, 내장 OIDC/Keycloak 인증을 포함하며, 규정 준수(EU AI법 포함)를 위한 불변 암호화 감사 추적을 제공하고, NATS JetStream으로 수평 확장합니다.',
		faq4Q: 'Model Context Protocol(MCP)이란 무엇인가요?', faq4A: 'Model Context Protocol(MCP)은 Claude Desktop, IDE 플러그인, 커스텀 클라이언트 같은 AI 어시스턴트가 외부 도구와 프로그래밍 방식으로 상호작용할 수 있게 하는 개방형 표준입니다. EDDI는 대화 관리, 에이전트 관리, 설정 자동화, 스케줄 관리, 진단에 걸친 48개 MCP 도구를 공개합니다.',
		faq5Q: 'EDDI가 프로덕션 워크로드에서 Flowise나 n8n을 대체할 수 있나요?', faq5A: 'EDDI는 Node.js 대신 JVM에서 유사한 비주얼 빌딩 목적을 수행합니다. Flowise, n8n과 달리 EDDI는 <code>eval()</code>이나 코드 블록을 사용하지 않고, 엔터프라이즈 급 동시성을 위해 Java 25 가상 스레드를 실행하며, OIDC/Keycloak 인증을 지원하고, MongoDB 또는 PostgreSQL에 데이터를 저장합니다. 규제 산업을 위해 설계되었습니다.',
	},
	gettingStarted: { title: '시작하기', description: 'EDDI를 설치하고, 첫 번째 에이전트를 만들고, 5분 안에 대화를 시작하세요.', heroTitle: 'EDDI 시작하기', heroSubtitle: 'EDDI를 설치하고, 첫 번째 에이전트를 만들고, 5분 안에 대화를 시작하세요.', prerequisitesTitle: '사전 요구사항', prereq1: '<strong>Docker</strong>(권장) 또는 Java 25+', prereq2: 'LLM 프로바이더 API 키 (OpenAI, Anthropic, Google Gemini, 또는 로컬 Ollama 인스턴스)', step1Title: '1. Docker로 EDDI 시작', step1Desc: 'EDDI를 실행하는 가장 빠른 방법:', step1After: 'EDDI가 <code>http://localhost:7070</code>에서 사용 가능합니다.', step2Title: '2. MCP로 연결', step2Desc: '<strong>Claude Desktop</strong> 또는 MCP 호환 클라이언트를 사용하는 경우, EDDI를 MCP 서버로 추가:', step2After: '이제 AI 어시스턴트에서 직접 EDDI의 48개 MCP 도구와 상호작용할 수 있습니다.', step3Title: '3. 첫 번째 에이전트 만들기', step3Desc: '<code>setup_agent</code> MCP 도구를 사용하여 한 번의 호출로 완전히 작동하는 에이전트를 만드세요:', step3After: '규칙, LLM 구성, 워크플로우, 에이전트를 생성하고 배포합니다 — 한 단계로.', step4Title: '4. 에이전트와 대화', step5Title: '5. 매니저 UI 열기', step5Desc: '<code>http://localhost:7070</code>으로 이동하여 EDDI 매니저로 에이전트, 워크플로우, 대화를 비주얼하게 관리하세요.', managerImageAlt: 'EDDI 매니저 UI 대시보드 미리보기', whatsNextTitle: '다음은?', nextAllFeatures: '모든 기능', nextAllFeaturesDesc: 'EDDI가 제공하는 모든 것을 탐색', nextMcpServer: 'MCP 서버', nextMcpServerDesc: '48개 MCP 도구 모두 보기', nextDocs: '문서 ↗', nextDocsDesc: '아키텍처와 API 심층 분석', nextWhyEddi: '왜 EDDI인가?', nextWhyEddiDesc: 'EDDI의 엔터프라이즈 케이스' },
	useCases: { title: '활용 사례', description: 'EDDI AI 오케스트레이션 플랫폼의 실제 배포 패턴과 활용 사례.', heroTitle: '활용 사례', heroSubtitle: 'EDDI 플랫폼의 실제 배포 패턴.', healthcare: '의료', healthcareDesc: '환자 접수 에이전트, 의료 FAQ 봇, 예약 스케줄링 — HIPAA 준수 및 EU AI법 대응을 위한 완전한 감사 추적.', finance: '금융 서비스', financeDesc: '규정 준수 로깅이 포함된 고객 지원 에이전트, 사기 탐지 어시스턴트, 암호화 감사 추적이 포함된 내부 기술 자료 챗봇.', ecommerce: '이커머스', ecommerceDesc: '제품 추천 에이전트, 주문 지원 봇, 다국어 고객 서비스 — 전문 에이전트 간 의도 기반 라우팅.', manufacturing: '제조', manufacturingDesc: '장비 유지보수 어시스턴트, 품질 관리 에이전트, 공급망 최적화 — 온프레미스 또는 프라이빗 클라우드에서 운영.', government: '정부', governmentDesc: '시민 문의 에이전트, 내부 프로세스 자동화, 문서 분석 — 클라우드 의존 없는 에어갭 환경에서.', devPlatforms: '개발자 플랫폼', devPlatformsDesc: '엔지니어링 팀을 위한 내부 AI 서비스 — CI/CD 파이프라인, 코드 리뷰, 문서 워크플로우에 통합되는 API 접근 가능 에이전트.' },
	featuresOverview: { title: '기능 한눈에 보기', description: 'EDDI를 엔터프라이즈 AI 오케스트레이터로 만드는 모든 기능 — EDDI 매니저 UI, Config-as-Code, 48개 MCP 도구, 보안 우선 아키텍처 등.', heroTitle: 'AI를 오케스트레이션하는 데', heroHighlight: '필요한 모든 것', heroDesc: 'EDDI는 AI 에이전트를 구축, 배포, 관리하기 위한 완전한 프로덕션 대응 플랫폼을 제공합니다 — 보일러플레이트 없이.', coreTitle: '코어 플랫폼', coreDesc: 'EDDI를 <strong>완전한 AI 오케스트레이션 플랫폼</strong>으로 만드는 핵심 기능.', managerCardTitle: '🖥️ EDDI 매니저', managerCardDesc: '에이전트를 비주얼하게 구축, 배포, 모니터링하기 위한 <strong>프로덕션 대응 React UI</strong> — 11개 로케일 i18n, 라이브 채팅 디버깅, 감사 대시보드.', configCardTitle: '⚙️ Config-as-Code', configCardDesc: '에이전트 로직은 JSON 구성이며, 컴파일된 코드가 아닙니다. 프롬프트 엔지니어가 즉시 반복 — <strong>재컴파일 불필요</strong>.', mcpCardTitle: '🔌 MCP 서버 (48개 도구)', mcpCardDesc: '<strong>Model Context Protocol</strong>을 통한 완전한 AI 네이티브 제어. Claude Desktop, Cursor, 커스텀 클라이언트가 에이전트를 프로그래밍 방식으로 관리.', securityCardTitle: '🔐 보안 우선', securityCardDesc: '<code>eval()</code> 없음, Vault 통합, 경로 순회 보호, OIDC/Keycloak, <strong>암호화 감사 추적</strong>.', perfCardTitle: '🚀 성능', perfCardDesc: 'Quarkus에서의 Java 25 가상 스레드 — I/O 바운드 LLM 워크로드를 위한 <strong>수백만 개의 경량 스레드</strong>.', multiCardTitle: '🤖 멀티 에이전트', multiCardDesc: '의도 기반 에이전트 디스커버리, 관리 대화, 에이전트 트리거, 여러 에이전트 간 <strong>A/B 라우팅</strong>.', engTitle: '엔지니어링 우수성', obsCardTitle: '📊 관측성', obsCardDesc: '모든 파이프라인 단계가 <strong>불변 감사 추적</strong>에 기록 — 토큰, 비용, 타이밍, 도구 호출.', cqCardTitle: '🧪 코드 품질', cqCardDesc: '<strong>1,500+ 테스트, 실패 제로.</strong> Checkstyle 경고 697에서 81로 감소. 매 머지마다 CI/CD 적용.', aiCardTitle: '🧩 AI 대응', aiCardDesc: '48개 MCP 도구, 예측 가능한 CRUD 패턴, 자기 문서화 API. <strong>코딩 에이전트</strong>를 위해 구축.' },
	pages: {
		manager: { title: 'EDDI 매니저', description: 'AI 에이전트를 비주얼하게 구축, 배포, 모니터링하기 위한 프로덕션 대응 React 관리 UI — 11개 로케일 i18n, 라이브 채팅 디버깅, 감사 대시보드.', heading1: '비주얼 에이전트 관리', para1: 'EDDI 매니저는 에이전트 구성부터 실시간 대화 모니터링까지 EDDI 플랫폼의 모든 측면에 대한 비주얼 제어를 제공하는 포괄적인 React 기반 관리 인터페이스입니다.', heading2: '주요 기능', items: ['<strong>비주얼 에이전트 빌더</strong> — 직관적인 드래그 앤 드롭 인터페이스로 에이전트 생성 및 구성', '<strong>라이브 채팅 디버깅</strong> — 전체 대화 검사로 실시간 에이전트 테스트', '<strong>감사 대시보드</strong> — 모든 에이전트의 토큰 사용량, 비용, 성능 모니터링', '<strong>11개 로케일 i18n</strong> — 아랍어 RTL 지원을 포함한 완전한 국제화', '<strong>인터랙티브 온보딩</strong> — 신규 사용자에게 플랫폼을 소개하는 가이드 투어', '<strong>리소스 관리</strong> — 규칙, 워크플로우, LLM 구성, 커넥터에 대한 CRUD 작업', '<strong>시크릿 볼트</strong> — 마스킹 표시가 포함된 안전한 API 키 관리'], heading3: '팀을 위한 설계', para2: '매니저를 통해 비개발자도 Java 코드를 건드리지 않고 에이전트 동작을 반복할 수 있습니다. 프롬프트 엔지니어는 규칙 수정, 대화 테스트, 변경 배포 — 모두 브라우저에서.' },
		mcpServer: { title: 'MCP 서버 — 48개 도구', description: 'EDDI는 Model Context Protocol을 통해 완전한 기능을 노출하여 Claude Desktop, Cursor, 커스텀 AI 클라이언트가 에이전트를 프로그래밍 방식으로 관리할 수 있게 합니다.', heading1: 'AI 네이티브 제어 플레인', para1: 'Model Context Protocol(MCP)은 AI 어시스턴트가 외부 도구와 상호작용할 수 있게 하는 개방형 표준입니다. EDDI는 플랫폼의 모든 측면을 포괄하는 <strong>48개 도구</strong>를 구현합니다.', heading2: '도구 카테고리', items: ['<strong>대화 도구</strong> — 에이전트와 채팅, 대화 관리, 기록 읽기', '<strong>관리 도구</strong> — 배포된 에이전트 목록, 검사, 관리', '<strong>설정 도구</strong> — <code>setup_agent</code>로 한 번의 호출로 완전한 에이전트 생성', '<strong>리소스 CRUD</strong> — 규칙, 워크플로우, LLM 구성, 커넥터의 완전한 생성/읽기/수정/삭제', '<strong>진단 도구</strong> — 헬스 체크, 구성 검사, 환경 진단', '<strong>스케줄 관리</strong> — 주기적 에이전트 작업 및 트리거 관리'], heading3: 'MCP 클라이언트 지원', para2: 'EDDI 에이전트는 대화 중에 <strong>외부 MCP 도구를 소비</strong>할 수도 있습니다. MCP 서버 엔드포인트를 구성하면, 에이전트가 대화 컨텍스트에 따라 도구를 자동 발견하고 호출합니다.' },
		configAsCode: { title: 'Configuration-as-Code', description: '에이전트 로직, 파이프라인, 도구 정의는 JSON 구성입니다 — 컴파일된 Java가 아닙니다.', heading1: 'JSON 기반 에이전트 로직', para1: 'EDDI에서 에이전트의 동작을 정의하는 모든 것은 <strong>JSON 구성 리소스</strong>입니다: 규칙(시스템 프롬프트), LLM 커넥터 설정, 워크플로우 파이프라인, 도구 구성, 배포 디스크립터.', heading2: '왜 중요한가', items: ['<strong>재컴파일 불필요</strong> — Java 코드가 아닌 JSON 업데이트로 에이전트 동작 변경', '<strong>프롬프트 엔지니어 친화적</strong> — 비개발자가 UI 또는 REST API로 규칙 수정', '<strong>버전 관리</strong> — JSON 구성이 Infrastructure-as-Code와 함께 Git에 저장', '<strong>핫 리로드</strong> — 변경 사항이 즉시 적용, 서버 재시작 불필요', '<strong>감사 가능</strong> — 모든 구성 변경이 불변 감사 추적에 기록'], heading3: '리소스 유형', para2: 'EDDI는 이러한 구성 리소스를 관리합니다: <strong>규칙</strong>(시스템 프롬프트), <strong>워크플로우</strong>(파이프라인 정의), <strong>LLM 커넥터</strong>(프로바이더 설정), <strong>HTTP 커넥터</strong>(외부 API 통합), <strong>에이전트</strong>(배포 디스크립터), <strong>환경</strong>(배포 대상).' },
		security: { title: '보안 우선 아키텍처', description: 'eval() 없음, 코드 실행 블록 없음. Vault 통합, 암호화 감사 추적, OIDC/Keycloak 인증.', heading1: '설계 기반 엔터프라이즈 보안', para1: 'EDDI는 설계 단계에서 보안 취약점의 전체 클래스를 제거합니다. <strong>eval()</strong> 없음, 코드 실행 블록 없음, 동적 코드 주입 없음 — 에이전트 동작은 선언적 JSON 구성만으로 정의.', heading2: '보안 기능', items: ['<strong>eval() 제로</strong> — 동적 코드 실행 없음 (CVSS 10.0 RCE 위험 제거)', '<strong>OIDC/Keycloak</strong> — 엔터프라이즈 인증 및 권한 부여', '<strong>Vault 통합</strong> — API 키를 위한 안전한 시크릿 관리', '<strong>경로 순회 보호</strong> — 모든 경계에서 입력 검증', '<strong>URL 검증</strong> — SSRF 및 리다이렉트 공격 방지', '<strong>암호화 감사 추적</strong> — 불변, 변조 방지 운영 로그', '<strong>EU AI법 대응</strong> — 규제 준수를 위한 내장 거버넌스 기능'] },
		performance: { title: '엔터프라이즈 성능', description: 'Quarkus에서의 Java 25 가상 스레드 — I/O 바운드 LLM 워크로드를 위한 수백만 개의 경량 스레드.', heading1: '확장을 위한 설계', para1: 'EDDI는 <strong>Java 25와 Quarkus</strong>에서 실행되며, 대규모 I/O 바운드 동시성을 위해 가상 스레드(Project Loom)를 활용합니다.', heading2: '성능 하이라이트', items: ['<strong>가상 스레드</strong> — 동시 LLM 호출을 위한 수백만 개의 경량 스레드', '<strong>GraalVM 네이티브 이미지</strong> — 서브 세컨드 부팅, 최소 메모리 풋프린트', '<strong>Quarkus 런타임</strong> — 클라우드 네이티브, 개발 모드 핫 리로드, 컨테이너 최적화', '<strong>NATS JetStream</strong> — 이벤트 기반 아키텍처로 수평 확장', '<strong>듀얼 데이터베이스</strong> — MongoDB 또는 PostgreSQL, 데이터베이스 추상 레이어'] },
		multiAgent: { title: '멀티 에이전트 오케스트레이션', description: '의도 기반 에이전트 디스커버리, 관리 대화, 에이전트 트리거, A/B 라우팅.', heading1: '지능형 에이전트 라우팅', para1: 'EDDI의 멀티 에이전트 시스템은 단순 로드 밸런싱을 넘어섭니다. 선언된 기능을 기반으로 사용자 요청을 가장 적합한 에이전트에 자동 라우팅하는 <strong>의도 기반 에이전트 디스커버리</strong>를 제공합니다.', heading2: '오케스트레이션 기능', items: ['<strong>에이전트 디스커버리</strong> — 에이전트가 의도를 선언하고 사용자 요청에 자동 매칭', '<strong>관리 대화</strong> — 의도+사용자당 하나의 대화, 자동 생성', '<strong>에이전트 트리거</strong> — 이벤트 기반 자동 에이전트 활성화', '<strong>A/B 라우팅</strong> — 동일 트래픽에 대해 다른 에이전트 테스트', '<strong>코디네이터 패턴</strong> — 에이전트가 전문 서브 에이전트에 위임'] },
		observability: { title: '관측성 및 감사 추적', description: '모든 파이프라인 단계가 불변 감사 추적에 기록 — 토큰, 비용, 타이밍, 도구 호출.', heading1: '완전한 가시성', para1: 'EDDI는 모든 대화, 파이프라인 단계, 도구 호출에 걸쳐 <strong>엔드투엔드 관측성</strong>을 제공합니다.', heading2: '관측성 기능', items: ['<strong>불변 감사 추적</strong> — 암호화 서명된 변조 방지 운영 로그', '<strong>토큰 및 비용 추적</strong> — 대화별, 에이전트별 사용량 메트릭', '<strong>파이프라인 트레이싱</strong> — 처리 파이프라인 각 단계에 대한 완전한 가시성', '<strong>Prometheus 메트릭</strong> — 모니터링 인프라를 위한 표준 메트릭 엔드포인트', '<strong>Grafana 대시보드</strong> — 운영 팀을 위한 사전 구축 대시보드', '<strong>CQRS 텔레메트리</strong> — 모든 시스템 운영의 이벤트 소싱 원장'] },
		codeQuality: { title: '코드 품질', description: '1,500+ 테스트, 실패 제로. Checkstyle 경고 697에서 81로 감소.', heading1: '엔지니어링 엄격성', para1: 'EDDI는 포괄적인 테스트, 정적 분석, CI/CD 품질 게이트를 통해 <strong>뛰어난 코드 품질</strong>을 유지합니다.', heading2: '품질 메트릭', items: ['<strong>1,500+ 테스트</strong> — 유닛, 통합, E2E 커버리지', '<strong>실패 제로</strong> — 매 빌드마다 클린 CI', '<strong>Checkstyle 적용</strong> — 697에서 81 경고로 감소', '<strong>MCP 도구 테스트</strong> — 48개 MCP 도구 전체의 포괄적 커버리지', '<strong>CI/CD 품질 게이트</strong> — 자동 체크로 리그레션 방지'] },
		aiReady: { title: 'AI 대응 아키텍처', description: '48개 MCP 도구, 예측 가능한 CRUD 패턴, 자기 문서화 API.', heading1: 'AI 협업을 위한 설계', para1: 'EDDI는 <strong>코딩 에이전트가 이를 관리할 것</strong>이라는 가정 하에 구축되었습니다.', heading2: 'AI 친화적 설계', items: ['<strong>예측 가능한 패턴</strong> — 일관된 리소스 네이밍, CRUD 규약, 오류 처리', '<strong>자기 문서화 API</strong> — OpenAPI 스펙과 MCP 도구 설명 자동 생성', '<strong>LLMs.txt 지원</strong> — llms.txt와 llms-full.txt를 통한 AI 발견 가능 사이트 콘텐츠', '<strong>MCP 우선</strong> — AI 어시스턴트 통합을 위해 설계된 48개 도구', '<strong>설정 자동화</strong> — <code>setup_agent</code>로 단일 호출 에이전트 생성'] },
		whyEddi: { title: '왜 EDDI인가?', description: '유일한 JVM 네이티브 비주얼 AI 오케스트레이션 미들웨어.', heading1: '엔터프라이즈 Java의 공백', para1: '엔터프라이즈 Java에는 <strong>비주얼 AI 오케스트레이션 미들웨어가 없습니다</strong>.', heading2: 'EDDI가 이 공백을 채웁니다', para2: 'EDDI는 <strong>배포 가능한 미들웨어 플랫폼</strong>이며 라이브러리가 아닙니다:', items: ['<strong>비주얼 관리 UI</strong> — 에이전트 구축과 모니터링을 위한 EDDI 매니저', '<strong>Configuration-as-Code</strong> — 에이전트 로직은 JSON, 컴파일된 Java가 아님', '<strong>48개 MCP 도구</strong> — Model Context Protocol을 통한 완전한 AI 네이티브 제어', '<strong>엔터프라이즈 보안</strong> — OIDC, Vault, 감사 추적, eval() 없음', '<strong>프로덕션 인프라</strong> — REST API, 대화 상태 관리, Prometheus 메트릭', '<strong>수평 확장</strong> — 분산 아키텍처를 위한 NATS JetStream'], heading3: '누가 EDDI를 사용해야 하나요?', items2: ['<strong>엔터프라이즈 Java 팀</strong> — JVM을 벗어나지 않고 AI 오케스트레이션이 필요', '<strong>프롬프트 엔지니어</strong> — Java 재컴파일 없이 반복하고 싶은', '<strong>규제 산업</strong> — 감사 추적과 EU AI법 준수가 필요한', '<strong>플랫폼 팀</strong> — 여러 부서를 위한 내부 AI 서비스를 구축하는'] },
		vsAlternatives: { title: 'EDDI vs. 대안', description: 'EDDI와 Spring AI, LangChain4j, Flowise, n8n 등 AI 오케스트레이션 접근법 비교.', heading1: '플랫폼 vs. 라이브러리', para1: '근본적 차이: EDDI는 <strong>배포 가능한 미들웨어 플랫폼</strong>이지 라이브러리가 아닙니다.', heading2: '비교', heading3a: 'vs. Spring AI / LangChain4j', para2: 'Spring AI와 LangChain4j는 훌륭한 <strong>라이브러리</strong>입니다. 하지만 라이브러리로는 REST 컨트롤러, 인증, 대화 관리, 감사 로그, 관리 UI를 직접 구축해야 합니다.', heading3b: 'vs. Flowise / n8n', para3: 'Flowise와 n8n은 Node.js 기반 비주얼 빌더입니다. EDDI는 JVM에서 유사한 목적:', vsItems: ['<strong>eval() 없음</strong> — CVSS 10.0 원격 코드 실행 위험 제거', '<strong>Java 25 가상 스레드</strong> — 엔터프라이즈 급 동시성 vs. 단일 스레드 Node.js', '<strong>OIDC/Keycloak</strong> — 엔터프라이즈 인증 vs. 기본 인증', '<strong>MongoDB/PostgreSQL</strong> — 프로덕션 데이터베이스 vs. SQLite'], heading3c: 'vs. AWS Bedrock / Azure AI Studio', para4: '클라우드 AI 플랫폼은 관리 인프라를 제공하지만 <strong>벤더 락인</strong>이 발생합니다. EDDI는 Docker가 실행되는 곳 어디서나 실행됩니다.' },
		compliance: { title: 'EU AI법 준수', description: '규제 준수를 위한 내장 거버넌스 기능 — 불변 감사 추적, 투명한 의사결정 로깅, 인적 감독 메커니즘.', heading1: '규제 대응 아키텍처', para1: 'EU AI법은 AI 시스템에 대한 포괄적 요구사항을 수립합니다. EDDI의 아키텍처는 준수에 필요한 <strong>기술적 기반</strong>을 제공합니다 — 나중에 추가하는 것이 아닌 처음부터 내장.', heading2: '준수 기능', items: ['<strong>불변 감사 추적</strong> — 모든 운영이 암호화 무결성으로 기록', '<strong>의사결정 투명성</strong> — 완전한 파이프라인 트레이싱으로 AI 의사결정 과정 표시', '<strong>인적 감독</strong> — 관리 UI로 인간 검토 및 개입 가능', '<strong>데이터 거버넌스</strong> — 접근 제어를 위한 OIDC/Keycloak, 시크릿을 위한 Vault', '<strong>위험 분류</strong> — 고위험 AI 시스템 요구사항을 지원하는 아키텍처', '<strong>재현성</strong> — Configuration-as-Code로 AI 동작 정확한 재현 가능'], heading3: '규제 산업을 위한 구축', para2: '의료, 금융 서비스, 정부 등 규제 산업은 플랫폼이 EU AI법 및 전 세계 유사 규제에서 요구하는 투명성, 감사 가능성, 제어 메커니즘을 제공한다는 확신 하에 EDDI를 배포할 수 있습니다.' },
	},
};

export default ko;
